repos:
  - repo: local
    hooks:
      - id: bench-commit-msg
        name: require bench
        language: pygrep
        entry: '(?i)^bench(?::|\s)+\d+'
        args:
          - --multiline
          - --negate
        stages:
          - commit-msg
